export const SEED_VARIETY_OPTIONS = [
  { value: 'Penaeus vannamei (SPF)', label: 'Penaeus vannamei (SPF Shrimp)' },
  { value: 'Penaeus monodon', label: 'Penaeus monodon (Black Tiger)' },
  { value: 'Macrobrachium rosenbergii', label: 'Freshwater Prawn (Scampi)' },
];

export const CROP_STATUS_OPTIONS = [
  { value: 'Active', label: 'Active Culture' },
  { value: 'Harvested', label: 'Completed / Harvested' },
  { value: 'Planned', label: 'Planned Stocking' },
  { value: 'Terminated', label: 'Terminated Early' },
];

export const MOCK_CROPS = [
  {
    id: 'crop-1',
    tankId: 'tank-1',
    tankName: 'Tank 1',
    cropName: 'Crop 1',
    seedVariety: 'Penaeus vannamei (SPF)',
    plCount: 0,
    stockingDate: '2026-06-15',
    expectedHarvestDate: '2026-10-15',
    expectedProduction: 0,
    expectedProductionKg: 0,
    expectedSellingPrice: 0,
    expectedSellingPricePerKg: 0,
    status: 'Active',
    notes: '',
    createdAt: '2026-06-15',
  },
  {
    id: 'crop-2',
    tankId: 'tank-2',
    tankName: 'Tank 2',
    cropName: 'Crop 2',
    seedVariety: 'Penaeus vannamei (SPF)',
    plCount: 0,
    stockingDate: '2026-07-01',
    expectedHarvestDate: '2026-10-30',
    expectedProduction: 0,
    expectedProductionKg: 0,
    expectedSellingPrice: 0,
    expectedSellingPricePerKg: 0,
    status: 'Active',
    notes: '',
    createdAt: '2026-07-01',
  },
  {
    id: 'crop-3',
    tankId: 'tank-3',
    tankName: 'Tank 3',
    cropName: 'Crop 3',
    seedVariety: 'Penaeus monodon',
    plCount: 0,
    stockingDate: '2026-05-20',
    expectedHarvestDate: '2026-09-20',
    expectedProduction: 0,
    expectedProductionKg: 0,
    expectedSellingPrice: 0,
    expectedSellingPricePerKg: 0,
    status: 'Active',
    notes: '',
    createdAt: '2026-05-20',
  },
  {
    id: 'crop-4',
    tankId: 'tank-5',
    tankName: 'Tank 5',
    cropName: 'Crop 4',
    seedVariety: 'Penaeus vannamei (SPF)',
    plCount: 0,
    stockingDate: '2026-07-20',
    expectedHarvestDate: '2026-08-25',
    expectedProduction: 0,
    expectedProductionKg: 0,
    expectedSellingPrice: 0,
    expectedSellingPricePerKg: 0,
    status: 'Active',
    notes: '',
    createdAt: '2026-07-20',
  },
];

export default MOCK_CROPS;
