export const MEDICINE_CATEGORY_OPTIONS = [
  { value: 'Disinfectant / Sanitizer', label: 'Disinfectant / Water Sanitizer' },
  { value: 'Probiotic', label: 'Probiotic (Soil / Water / Feed)' },
  { value: 'Vitamin / Supplement', label: 'Vitamin & Immunity Supplement' },
  { value: 'Mineral', label: 'Mineral Supplement (Ca/Mg/K)' },
  { value: 'Antibiotic / Therapeutic', label: 'Therapeutic / Parasiticide' },
];

export const MEDICINE_UNIT_OPTIONS = [
  { value: 'Litre', label: 'Litre (L)' },
  { value: 'Kg', label: 'Kilogram (Kg)' },
  { value: 'Grams', label: 'Grams (g)' },
  { value: 'PPM', label: 'PPM' },
  { value: 'ml', label: 'Millilitre (ml)' },
];

export const MEDICINE_STATUS_OPTIONS = [
  { value: 'Completed', label: 'Completed' },
  { value: 'Scheduled', label: 'Scheduled' },
  { value: 'Missed', label: 'Missed' },
];

export const MOCK_MEDICINE_RECORDS = [
  {
    id: 'med-1',
    cropId: 'crop-1',
    cropName: 'Crop 1',
    tankId: 'tank-1',
    tankName: 'Tank 1',
    medicineName: 'Medicine 1',
    category: 'Disinfectant / Sanitizer',
    dosage: '1 Litre/Acre',
    quantity: 0,
    unit: 'Litre',
    applicationDate: '2026-08-05',
    applicationTime: '07:00 AM',
    cost: 0,
    purpose: 'Treatment',
    status: 'Completed',
    notes: '',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-2',
    cropId: 'crop-1',
    cropName: 'Crop 1',
    tankId: 'tank-1',
    tankName: 'Tank 1',
    medicineName: 'Medicine 2',
    category: 'Probiotic',
    dosage: '1 Kg/Acre',
    quantity: 0,
    unit: 'Kg',
    applicationDate: '2026-08-05',
    applicationTime: '10:00 AM',
    cost: 0,
    purpose: 'Treatment',
    status: 'Completed',
    notes: '',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-3',
    cropId: 'crop-2',
    cropName: 'Crop 2',
    tankId: 'tank-2',
    tankName: 'Tank 2',
    medicineName: 'Medicine 3',
    category: 'Vitamin / Supplement',
    dosage: '1 g/kg',
    quantity: 0,
    unit: 'Grams',
    applicationDate: '2026-08-05',
    applicationTime: '04:00 PM',
    cost: 0,
    purpose: 'Treatment',
    status: 'Completed',
    notes: '',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-4',
    cropId: 'crop-3',
    cropName: 'Crop 3',
    tankId: 'tank-3',
    tankName: 'Tank 3',
    medicineName: 'Medicine 4',
    category: 'Mineral',
    dosage: '1 Kg/Acre',
    quantity: 0,
    unit: 'Kg',
    applicationDate: '2026-08-06',
    applicationTime: '06:00 AM',
    cost: 0,
    purpose: 'Treatment',
    status: 'Scheduled',
    notes: '',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-5',
    cropId: 'crop-1',
    cropName: 'Crop 1',
    tankId: 'tank-1',
    tankName: 'Tank 1',
    medicineName: 'Medicine 5',
    category: 'Antibiotic / Therapeutic',
    dosage: '1 Litre/Acre',
    quantity: 0,
    unit: 'Litre',
    applicationDate: '2026-08-03',
    applicationTime: '08:00 AM',
    cost: 0,
    purpose: 'Treatment',
    status: 'Missed',
    notes: '',
    createdAt: '2026-08-03',
  },
];

export default MOCK_MEDICINE_RECORDS;
