export const MEDICINE_CATEGORY_OPTIONS = [
  { value: 'Disinfectant / Sanitizer', label: 'Disinfectant / Water Sanitizer' },
  { value: 'Probiotic', label: 'Probiotic (Soil / Water / Feed)' },
  { value: 'Vitamin / Supplement', label: 'Vitamin & Immunity Supplement' },
  { value: 'Mineral', label: 'Mineral Supplement (Ca/Mg/K)' },
  { value: 'Antibiotic / Therapeutic', label: 'Therapeutic / Parasiticide' },
];

export const MEDICINE_UNIT_OPTIONS = [
  { value: 'Litre', label: 'Litre (L)' },
  { value: 'Kg', label: 'Kilogram (Kg)' },
  { value: 'Grams', label: 'Grams (g)' },
  { value: 'PPM', label: 'PPM' },
  { value: 'ml', label: 'Millilitre (ml)' },
];

export const MEDICINE_STATUS_OPTIONS = [
  { value: 'Completed', label: 'Completed' },
  { value: 'Scheduled', label: 'Scheduled' },
  { value: 'Missed', label: 'Missed' },
];

export const MOCK_MEDICINE_RECORDS = [
  {
    id: 'med-1',
    cropId: 'crop-1',
    cropName: 'Vannamei Season 2026 Batch A',
    tankId: 'tank-1',
    tankName: 'Pond P-1 (Vannamei Main)',
    medicineName: 'BKC 80% Sanitizer',
    category: 'Disinfectant / Sanitizer',
    dosage: 2.5,
    unit: 'Litre',
    applicationDate: '2026-08-05',
    applicationTime: '07:00 AM',
    cost: 1750,
    purpose: 'Water disinfection & bacterial pathogen reduction prior to molting cycle',
    status: 'Completed',
    notes: 'Diluted with pond water and broadcasted uniformly around paddlewheel aerators.',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-2',
    cropId: 'crop-1',
    cropName: 'Vannamei Season 2026 Batch A',
    tankId: 'tank-1',
    tankName: 'Pond P-1 (Vannamei Main)',
    medicineName: 'Bio-Soil Gut & Water Probiotic',
    category: 'Probiotic',
    dosage: 5.0,
    unit: 'Kg',
    applicationDate: '2026-08-05',
    applicationTime: '10:00 AM',
    cost: 3200,
    purpose: 'Organic sludge decomposition & toxic ammonia reduction',
    status: 'Completed',
    notes: 'Fermented with jaggery for 12 hours prior to application.',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-3',
    cropId: 'crop-2',
    cropName: 'Vannamei Summer Crop 2',
    tankId: 'tank-2',
    tankName: 'Pond P-2 (South Sector)',
    medicineName: 'Vitamin C & Immunostimulant',
    category: 'Vitamin / Supplement',
    dosage: 500,
    unit: 'Grams',
    applicationDate: '2026-08-05',
    applicationTime: '04:00 PM',
    cost: 950,
    purpose: 'Stress relief & shell hardness enhancement',
    status: 'Completed',
    notes: 'Coated over feed pellets using binder gel.',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-4',
    cropId: 'crop-3',
    cropName: 'Black Tiger Premium Cultivation',
    tankId: 'tank-3',
    tankName: 'Pond P-3 (North Field)',
    medicineName: 'Aqua-Mineral Mix (Ca/Mg/K)',
    category: 'Mineral',
    dosage: 25.0,
    unit: 'Kg',
    applicationDate: '2026-08-06',
    applicationTime: '06:00 AM',
    cost: 4500,
    purpose: 'Post-molt shell mineralization & alkalinity boost',
    status: 'Scheduled',
    notes: 'Scheduled for morning application after night molting event.',
    createdAt: '2026-08-05',
  },
  {
    id: 'med-5',
    cropId: 'crop-1',
    cropName: 'Vannamei Season 2026 Batch A',
    tankId: 'tank-1',
    tankName: 'Pond P-1 (Vannamei Main)',
    medicineName: 'Formalin 37% Treatment',
    category: 'Antibiotic / Therapeutic',
    dosage: 10.0,
    unit: 'Litre',
    applicationDate: '2026-08-03',
    applicationTime: '08:00 AM',
    cost: 2100,
    purpose: 'External protozoan parasite control (Zoothamnium)',
    status: 'Missed',
    notes: 'Postponed due to low morning dissolved oxygen levels.',
    createdAt: '2026-08-03',
  },
];

export default MOCK_MEDICINE_RECORDS;
